# Generated by Django 5.0.6 on 2024-11-21 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Kino Janri', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Kino sarlavhasi', max_length=555)),
                ('description', models.TextField(help_text='Kino tavsilotlari')),
                ('duration', models.IntegerField(help_text='Kino davomiyligi (minutda)')),
                ('movie_type', models.CharField(help_text='Kino janri', max_length=255)),
                ('studios', models.CharField(help_text='Ishlab chiqaruvchi studio', max_length=350)),
                ('release_date', models.DateField(help_text='Kino premyerasi sana')),
                ('rating', models.FloatField(help_text='Kino reytingi')),
                ('views', models.IntegerField(help_text="Ko'rishlar soni")),
                ('is_active', models.BooleanField(default=True, help_text='Aktivligi')),
                ('quality', models.CharField(choices=[('hd', 'HD'), ('full_hd', 'Full HD'), ('_4k', '4K')], max_length=20)),
                ('scores', models.FloatField(help_text='Scoring')),
                ('status', models.CharField(choices=[('released', 'Released'), ('coming_soon', 'Coming Soon'), ('in_production', 'In Production'), ('post_production', 'Post Production'), ('cancelled', 'Cancelled'), ('announced', 'Announced'), ('airing', 'Airing')], default='coming_soon', help_text='Kino statusi', max_length=25)),
                ('image', models.ImageField(help_text='Kino banneri', upload_to='movie_images/')),
                ('video', models.FileField(help_text='Kino/Treyler fayli', upload_to='movies/')),
                ('thumb', models.FileField(blank=True, help_text='Thumb fayli', null=True, upload_to='movie_thumbs/')),
                ('type', models.CharField(choices=[('regular', 'Regular'), ('banner', 'Banner')], default='regular', help_text='Kino joylashuvi', max_length=20)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovieGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.genre')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
